### PR TITLE
added 7d view and included new column

### PR DESCRIPTION
**Pull request by m0atz**
included 7 day change column, i found this useful.

### CODE REVIEW

**Comment by bichenkk** [comment]
@m0atz Thanks!!!...I am doing a big change due to auto refresh 1.0.0 release. I will add this to it. :)

**Comment by m0atz** [comment]
nice, looking forward to the updates

**Comment by Jbz797** [comment]
Some news about the 1.0.0 release ?

**Comment by bichenkk** [comment]
@Jbz797 I am sorry. I am a bit busy these weeks studying (it s the final exam period now haha) and I am picking up the progress soon! Thanks for the support!

**Pull request closed without merging**
